### ISSUE TITLE
Unhandled exception.  Latest Jenkins Build.  Spigot 1.8

### ISSUE THREAD

**Issue by Lostwave** [tehbeard/BeardStat#59]
2015-02-17 14:41:02 [WARN] [BeardStat] Task #31 for BeardStat v1.0.0-SNAPSHOT-Ambrosia-git-"9d5a12c" generated an exception
java.util.ConcurrentModificationException
        at java.util.HashMap$HashIterator.nextEntry(Unknown Source) ~[?:1.7.0_07]
        at java.util.HashMap$ValueIterator.next(Unknown Source) ~[?:1.7.0_07]
        at com.tehbeard.beardstat.manager.EntityStatManager.saveCache(EntityStatManager.java:90) ~[?:?]
        at com.tehbeard.beardstat.bukkit.BukkitPlugin$DbFlusher.run(BukkitPlugin.java:332) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.8.jar:git-Spigot-8a983f9-e81edfc]
        at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.8.jar:git-Spigot-8a983f9-e81edfc]
        at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:709) [spigot-1.8.jar:git-Spigot-8a983f9-e81edfc]
        at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot-1.8.jar:git-Spigot-8a983f9-e81edfc]
        at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:634) [spigot-1.8.jar:git-Spigot-8a983f9-e81edfc]
        at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:537) [spigot-1.8.jar:git-Spigot-8a983f9-e81edfc]
        at java.lang.Thread.run(Unknown Source) [?:1.7.0_07]

Its because line 107: 
uuidCache.remove(blob.getUUID());

In a foreach loop

**Comment by tehbeard** [comment]
An old build at this point, I'm going to merge the spigotmc branch into develop.

**Comment by Lostwave** [comment]
Still getting this error:
2015-02-18 09:08:47 [WARN] [BeardStat] Task #31 for BeardStat v1.0.0-SNAPSHOT-Ambrosia-git-"258811a" generated an exception
java.util.ConcurrentModificationException
        at java.util.HashMap$HashIterator.nextEntry(Unknown Source) ~[?:1.7.0_07]
        at java.util.HashMap$ValueIterator.next(Unknown Source) ~[?:1.7.0_07]
        at com.tehbeard.beardstat.manager.EntityStatManager.saveCache(EntityStatManager.java:101) ~[?:?]
        at com.tehbeard.beardstat.bukkit.BukkitPlugin$DbFlusher.run(BukkitPlugin.java:332) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.8.jar:git-Spigot-8a983f9-e81edfc]
        at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.8.jar:git-Spigot-8a983f9-e81edfc]
        at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:709) [spigot-1.8.jar:git-Spigot-8a983f9-e81edfc]
        at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot-1.8.jar:git-Spigot-8a983f9-e81edfc]
        at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:634) [spigot-1.8.jar:git-Spigot-8a983f9-e81edfc]
        at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:537) [spigot-1.8.jar:git-Spigot-8a983f9-e81edfc]
        at java.lang.Thread.run(Unknown Source) [?:1.7.0_07]

Different line, but same issue.

**Comment by Lostwave** [comment]
Also got this message when a new player logged on:
2015-02-18 12:23:49 [INFO] Sigge_02[/90.228.249.104:49688] logged in with entity id 432165 at ([Westeros] 20.5, 181.0, -1167.5)
2015-02-18 12:23:49 [ERROR] [BeardStat] =========================================
2015-02-18 12:23:49 [ERROR] [BeardStat] |             DATABASE ERROR            |
2015-02-18 12:23:49 [ERROR] [BeardStat] =========================================
2015-02-18 12:23:49 [ERROR] [BeardStat]
2015-02-18 12:23:49 [ERROR] [BeardStat] Caused by script: sql/entity/getEntityData
2015-02-18 12:23:49 [ERROR] [BeardStat]
2015-02-18 12:23:49 [ERROR] [BeardStat] Mysql error code: 1048
2015-02-18 12:23:49 [ERROR] [BeardStat] Error code [1048] not found (or not supplied!), either check the error code online, or post on the dev.bukkit.org/server-mods/beardstat page
2015-02-18 12:23:49 [ERROR] [BeardStat] Exception Detail:
2015-02-18 12:23:49 [ERROR] [BeardStat] Column 'name' cannot be null
2015-02-18 12:23:49 [WARN] com.tehbeard.beardstat.NoRecordFoundException: Failed to locate stat record for null [player] uuid: ce89c96c407046359a1d2258373b542a
2015-02-18 12:23:49 [WARN]      at com.tehbeard.beardstat.manager.ASyncLoadBlob.run(ASyncLoadBlob.java:44)
2015-02-18 12:23:49 [WARN]      at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
2015-02-18 12:23:49 [WARN]      at java.util.concurrent.FutureTask$Sync.innerRun(Unknown Source)
2015-02-18 12:23:49 [WARN]      at java.util.concurrent.FutureTask.run(Unknown Source)
2015-02-18 12:23:49 [WARN]      at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
2015-02-18 12:23:49 [WARN]      at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
2015-02-18 12:23:49 [WARN]      at java.lang.Thread.run(Unknown Source)

**Comment by tehbeard** [comment]
Ahh I see the problem now, I'm looping over that map that is being modified.

I'll rework the code when I get back to use an iterator instead, that should solve the problem.

**Comment by Lostwave** [comment]
This is fixed.  Thanks!

There is one more thing.  If I request something for a player who doesn't exist (i misspelled my name) it gives me an error.  I assume this is just because its a debug build or something, so probably a non issue.

>laston lostwtave
2015-02-20 08:48:09 [ERROR] [BeardStat] WARNING: BeardStat has encountered an error.
2015-02-20 08:48:09 [ERROR] [BeardStat] An error occured loading a stat blob for 31d7efef-054c-393b-8e8c-413d6e5a944b
2015-02-20 08:48:09 [ERROR] [BeardStat] =========
2015-02-20 08:48:09 [ERROR] [BeardStat] BeardStat
2015-02-20 08:48:09 [ERROR] [BeardStat] =========
2015-02-20 08:48:09 [ERROR] [BeardStat] BeardStat encountered an error, please submit the following info + stack trace to the dev bukkit page (http://
dev.bukkit.org/server-mods/BeardStat/
2015-02-20 08:48:09 [ERROR] [BeardStat]
2015-02-20 08:48:09 [ERROR] [BeardStat] BeardStat version: 1.0.0-SNAPSHOT-Ambrosia-git-"bcf3912"
2015-02-20 08:48:09 [ERROR] [BeardStat]
2015-02-20 08:48:09 [WARN] com.tehbeard.beardstat.BeardStatRuntimeException: An error occured loading a stat blob for 31d7efef-054c-393b-8e8c-413d6e5a
944b
2015-02-20 08:48:09 [WARN]      at com.tehbeard.beardstat.manager.EntityStatManager.getPlayer(EntityStatManager.java:64)
2015-02-20 08:48:09 [WARN]      at com.tehbeard.beardstat.bukkit.commands.LastOnCommand.onCommand(LastOnCommand.java:41)
2015-02-20 08:48:09 [WARN]      at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
2015-02-20 08:48:09 [WARN]      at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
2015-02-20 08:48:09 [WARN]      at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:646)
2015-02-20 08:48:09 [WARN]      at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchServerCommand(CraftServer.java:632)
2015-02-20 08:48:09 [WARN]      at net.minecraft.server.v1_8_R1.DedicatedServer.aM(DedicatedServer.java:353)
2015-02-20 08:48:09 [WARN]      at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:317)
2015-02-20 08:48:09 [WARN]      at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:634)
2015-02-20 08:48:09 [WARN]      at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:537)
2015-02-20 08:48:09 [WARN]      at java.lang.Thread.run(Unknown Source)
2015-02-20 08:48:09 [WARN] Caused by: java.lang.IllegalStateException: Promise was rejected
2015-02-20 08:48:09 [WARN]      at com.tehbeard.beardstat.utils.deferred.promise.Deferred.getValue(Deferred.java:295)
2015-02-20 08:48:09 [WARN]      at com.tehbeard.beardstat.manager.EntityStatManager.getPlayer(EntityStatManager.java:62)
2015-02-20 08:48:09 [WARN]      ... 10 more
2015-02-20 08:48:09 [WARN] Caused by: com.tehbeard.beardstat.NoRecordFoundException: Failed to locate stat record for null [player] uuid: 31d7efef054c
393b8e8c413d6e5a944b
2015-02-20 08:48:09 [WARN]      at com.tehbeard.beardstat.manager.ASyncLoadBlob.run(ASyncLoadBlob.java:44)
2015-02-20 08:48:09 [WARN]      at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
2015-02-20 08:48:09 [WARN]      at java.util.concurrent.FutureTask$Sync.innerRun(Unknown Source)
2015-02-20 08:48:09 [WARN]      at java.util.concurrent.FutureTask.run(Unknown Source)
2015-02-20 08:48:09 [WARN]      at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
2015-02-20 08:48:09 [WARN]      at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
2015-02-20 08:48:09 [WARN]      ... 1 more
2015-02-20 08:48:09 [ERROR] [BeardStat]
2015-02-20 08:48:09 [ERROR] [BeardStat] =========
2015-02-20 08:48:09 [INFO] player lostwtave not found

**Comment by tehbeard** [comment]
it's a "bug" with the error reporting when using the getPlayer method, for now I commented out the errorHandler output for that command.

**Comment by Lostwave** [comment]
Appears to be all fixed.
